name: movies_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  fvm: ^3.2.1
  go_router: ^16.0.0
  bloc: ^9.0.0
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  fluttertoast: ^8.2.12
  flutter_dotenv: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/home.svg
    - assets/icons/search.svg
    - .env
